# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc59dbfa748cc13de0a295544d893bdc8ef4a1684c1334490f8ba2b5ddb5b225f5c0a7d6ba660b67014f0bedd0dcb705e02e2fd75f1da84bff95c3036b1e751f

test:
  secret_key_base: 0e33c2196e5d7c81020d9f957d9adf769468225d0c58b397946c98fc96901299bcbdcb7c4b0739b52360f369b802b70ac0d350bf4f9d0802134c94595aa8265c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
